### ISSUE TITLE
当使用cpu训练时候，cpu的利用率非常差

### ISSUE THREAD

**Issue by sun-yao** [bai-shang/crnn_ctc_ocr.Tensorflow#20]
作者你好，我测试了一下你这个网络结构在cpu上的训练，速度非常慢。但是我并不是对速度慢存在疑惑，主要是cpu的利用率非常低，我实在想不出是哪个环节使得cpu的利用率非常低？ 你这个网络，前面就是卷积加了两个bn层，后面接了双向循环网络， 这究竟是哪个环节引起的问题呢？

**Comment by bai-shang** [comment]
本来整个tf的从数据读取到训练，都不是以CPU优化的，慢也是正常。

**Comment by sun-yao** [comment]
我说的是训练慢，并非数据预处理慢。训练慢，也并非是cpu优化什么原因。我已经找到原因了。

**Comment by Drbridge** [comment]
@sun-yao 请问最后训练慢的原因是什么

**Comment by sun-yao** [comment]
就是这套源码中训练的每一步都有推理预测，推理使用的ctc解码函数比较耗时，更换一下解码函数就行了

发自我的iPhone8

**Comment by Drbridge** [comment]
@sun-yao  十分感谢回复！！！
